export { default as PlatformAdminDashboardLayout } from './PlatformAdminDashboardLayout'
export { default as Overview } from './Overview'
export { default as Users } from './Users'
export { default as Tasks } from './Tasks'
export { default as CreateTask } from './CreateTask'
export { default as EditTask } from './EditTask'
export { default as TaskHelp } from './TaskHelp'
export { default as Categories } from './Categories'

export { default as Students } from './tabs/students'
export { default as Teachers } from './tabs/teachers'
export { default as Parents } from './tabs/parents'
export { default as SocialWorkers } from './tabs/socialWorkers'
export { default as SchoolAdmins } from './tabs/schoolAdmins'

export { default as UserDetails } from './UserDetails'
